server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cmf_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6381
    password: ""  # 빈 문자열로 설정 (비밀번호 없음)

    # Kafka 설정
    kafka:
      bootstrap-servers: localhost:9092
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        properties:
          spring.json.add.type.headers: false
          spring.json.trusted.packages: "cmf.commitField.*"
      consumer:
        group-id: commitfield-notifications
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
          spring.json.trusted.packages: "cmf.commitField.*"
          spring.json.value.default.type: "cmf.commitField.global.kafka.message.NotificationMessage"
        auto-offset-reset: latest
        enable-auto-commit: false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: "temp-client-id"
            client-secret: "temp-client-secret"
            scope:
              - user:email
              - read:user

aws:
  access-key-id: "dummy-key"
  secret-access-key: "dummy-secret"

github:
  token: "dummy-token"

springdoc:
  swagger-ui:
    path: /api-test

logging:
  level:
    org.hibernate.SQL: DEBUG