#server:
#  port: 8090
#  shutdown: graceful # 천천히 종료
#spring:
#  autoconfigure:
#    exclude:
#  lifecycle:
#    # 스프링부트가 종료 요청을 받은 후 기다려줄 수 있는 최대한의 시간
#    timeout-per-shutdown-phase: 1h
#  datasource:
#    url: jdbc:mysql://172.17.0.1:3306/cmf_db
#    username: root
#    password: cmf55!!
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  data:
#    redis:
#      host: 172.17.0.1
#      port: 6379
#      password: ${spring.redis.password}
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: false
#        highlight_sql: false
#        use_sql_comments: false
#logging:
#  level:
#    org.hibernate.SQL: INFO
#    org.hibernate.orm.jdbc.bind: INFO
#    org.hibernate.orm.jdbc.extract: INFO
#    org.springframework.transaction.interceptor: INFO
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info,metrics  # 특정 엔드포인트만 공개